# Configuration File for Admin Scripts

# Define chains and attributes to be used in a given environment

[chains]

[chains.local]

[chains.local.anvil]
chain_id = 31337
http_rpc_url = "http://localhost:8545"
ws_rpc_url = "ws://localhost:8546"

[chains.test]

[chains.test.base-sepolia]
chain_id = 84532
http_rpc_url = "https://sepolia.base.org"
ws_rpc_url = ""

[chains.prod]

[chains.prod.base]
chain_id = 8453
http_rpc_url = "https://mainnet.base.org"
ws_rpc_url = ""

[domains]

[domains.local]
web-client = "localhost:3000"

[domains.test]
web-client = "basechain.email"

[domains.prod]
web-client = "basechain.email"

